DROP TABLE IF EXISTS MEET_UP;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS MEET_UP_USERS;
DROP TABLE IF EXISTS TEMPERATURE_PARAMETRY;

CREATE TABLE MEET_UP (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  DIRECTION VARCHAR(250) NOT NULL,
  MEET_UP_DATE DATE NOT NULL
);

CREATE TABLE USER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL,
  USER_NAME VARCHAR(250) NOT NULL,
  PASSWORD VARCHAR(250) NULL
);

CREATE TABLE MEET_UP_USERS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(250) NOT NULL,
  MEET_UP_ID VARCHAR(250) NOT NULL,
  USER_ATTENTED BOOLEAN NOT NULL,
  USER_MEET_UP_DATE DATE NOT NULL
);

CREATE TABLE TEMPERATURE_PARAMETRY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MAXIMUM_TEMPERATURE DECIMAL  NULL,
  MINIMUM_TEMPERATURE DECIMAL  NULL,
  AMOUNT_BEER_BY_PERSON DECIMAL NOT NULL
);

INSERT INTO TEMPERATURE_PARAMETRY (MAXIMUM_TEMPERATURE, MINIMUM_TEMPERATURE,AMOUNT_BEER_BY_PERSON) VALUES
  (20.0,24.0,1),
  (NULL, 20.0, 0.75),
  (24.0,NULL,2);  

  

