DROP TABLE IF EXISTS MEET_UP;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS MEET_UP_USERS;
DROP TABLE IF EXISTS TEMPERATURE_PARAMETRY;

CREATE TABLE MEET_UP (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  DIRECTION VARCHAR(250) NOT NULL,
  MEET_UP_DATE DATE NOT NULL
);

CREATE TABLE USER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  FIRST_NAME VARCHAR(250) NOT NULL,
  LAST_NAME VARCHAR(250) NOT NULL
);

CREATE TABLE MEET_UP_USERS (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  USER_ID VARCHAR(250) NOT NULL,
  MEET_UP_ID VARCHAR(250) NOT NULL,
  USER_ATTENTED BOOLEAN NOT NULL,
  USER_MEET_UP_DATE DATE NOT NULL
);

CREATE TABLE TEMPERATURE_PARAMETRY (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  MAXIMUM_TEMPERATURE DECIMAL  NULL,
  MINIMUM_TEMPERATURE DECIMAL  NULL,
  AMOUNT_BEER_BY_PERSON DECIMAL NOT NULL
);

INSERT INTO TEMPERATURE_PARAMETRY (MAXIMUM_TEMPERATURE, MINIMUM_TEMPERATURE,AMOUNT_BEER_BY_PERSON) VALUES
  (20.0,24.0,1),
  (NULL, 20.0, 0.75),
  (24.0,NULL,2);
  
INSERT INTO MEET_UP (DIRECTION,MEET_UP_DATE) VALUES
  ('AV CASEROS 2138',CURRENT_TIMESTAMP()),
  ('AV SAN JUAN 2138',CURRENT_TIMESTAMP() - 1),
  ('ALBERTI 454',CURRENT_TIMESTAMP() + 4);
  
  INSERT INTO USER (FIRST_NAME, LAST_NAME) VALUES
  ('LEANDRO','SALOMON'),
  ('IGNACIO','VARELA'),
  ('ROMINA','QUISPE'),
  ('SEBASTIAN','SANIO'),
  ('JOAQUIN','VALVERDE'),
  ('RICARDO','FORMICA'),
  ('JUAN','FERREYRA');
  
  INSERT INTO MEET_UP_USERS (USER_ID,MEET_UP_ID,USER_MEET_UP_DATE,USER_ATTENTED) VALUES
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'LEANDRO' AND LAST_NAME = 'SALOMON'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV CASEROS 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'IGNACIO' AND LAST_NAME = 'VARELA'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV CASEROS 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'SEBASTIAN' AND LAST_NAME = 'SANIO'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV CASEROS 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'JOAQUIN' AND LAST_NAME = 'VALVERDE'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV CASEROS 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'RICARDO' AND LAST_NAME = 'FORMICA'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV CASEROS 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'LEANDRO' AND LAST_NAME = 'SALOMON'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV SAN JUAN 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'IGNACIO' AND LAST_NAME = 'VARELA'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV SAN JUAN 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'JUAN' AND LAST_NAME = 'FERREYRA'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV SAN JUAN 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'RICARDO' AND LAST_NAME = 'FORMICA'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'AV SAN JUAN 2138'),CURRENT_TIMESTAMP(),false),
  ((SELECT ID FROM USER WHERE FIRST_NAME = 'LEANDRO' AND LAST_NAME = 'SALOMON'), (SELECT ID FROM MEET_UP WHERE DIRECTION = 'ALBERTI 454'),CURRENT_TIMESTAMP(),false);
  

